addons:
  apt:
    update: true

before_install:
  - sudo apt-get install -y rspamd

script:
  - ./combined.sh

deploy:
  provider: script
  skip_cleanup: true
  script:
    - ./ci/sign.sh
  on:
    repo: 'griff/whitelist'
    branch: master
