addons:
  apt:
    update: true

before_install:
  - sudo apt-get install -y rspamd

install:
  - echo 'xev.maven-group.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHPMomsIMLn7UXwmS1Ghm9Q8eCyrDbBcMA8ik3AvCwin' >> $HOME/.ssh/known_hosts

script:
  - ./combined.sh

before_deploy:
  - if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]] ; then
      openssl aes-256-cbc -K $encrypted_241552de5a9b_key -iv $encrypted_241552de5a9b_iv -in keypair.ucl.enc -out keypair.ucl -d ;
      openssl aes-256-cbc -K $encrypted_241552de5a9b_key -iv $encrypted_241552de5a9b_iv -in id_ed25519.enc -out /tmp/id_ed25519 -d ;
      chmod 600 /tmp/id_ed25519 ;
      eval "$(ssh-agent -s)" ;
      ssh-add /tmp/id_ed25519 ;
    fi
deploy:
  provider: script
  skip_cleanup: true
  script:
    - ./ci/sign.sh
    - rsync -rli --progress --checksum output/ brian@xev.maven-group.org:/data/xev-files.maven-group.org/whitelist/
  on:
    repo: 'griff/whitelist'
    branch: master
