language: nix

install:
  - nix-shell --command "echo Hello"

script:
  - nix-shell --run ./ci/build.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: site/_site/
  fqdn: whitelist.maven-group.org
  on:
    branch: master
