language: nix

install:
  - echo 'xev.maven-group.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHPMomsIMLn7UXwmS1Ghm9Q8eCyrDbBcMA8ik3AvCwin' >> $HOME/.ssh/known_hosts

script:
  - nix-shell --run ./combined.sh

before_deploy:
  - if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]] ; then
      ./ci/decrypt.sh ;
    fi
deploy:
  provider: script
  skip_cleanup: true
  script:
    - nix-shell --run ./ci/deploy.sh
  on:
    repo: 'griff/whitelist'
    branch: master
