name: "Build and deploy"
on:
  push:
  pull_request:
  schedule:
    - cron:  '* * * * 6'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v7
    - name: "Debug if"
      env:
        MY_REF: ${{ github.ref }}
      run: echo $MY_REF
    - name: "Install dependencies"
      run: nix-shell --command "echo Hello"
    - name: Build
      env:
        GPG_SECRETS_PASSWORD: ${{ secrets.GPG_SECRETS_PASSWORD }}
      run: nix-shell --run ./ci/build.sh
    - name: Install SSH Client 🔑
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - name: Deploy pages 🚀
      if: "github.ref == 'refs/heads/master'"
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        SSH: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: site # The folder the action should deploy.
