name: "Build and deploy"
on:
  push:
  pull_request:
  schedule:
    - cron:  '* * * * 6'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v7
    - name: "Install dependencies"
      env:
        MY_REF: ${{ github.ref }}
      run: |
        echo $MY_REF
        nix-shell --command "echo Hello"
    - name: Build
      env:
        GPG_SECRETS_PASSWORD: ${{ secrets.GPG_SECRETS_PASSWORD }}
      run: nix-shell --run ./ci/build.sh
    - name: Deploy pages 🚀
      if: "github.ref == 'master'"
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: site # The folder the action should deploy.
