name: "Update Ruby Gems"
on:
  schedule:
    - cron:  '0 12 * * 1'
  repository_dispatch:
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - run: 'echo "Event: ${{ github.event_name }}"'
    - run: 'echo "Action: ${{ github.event.action }}"'
    - run: 'cat "${{ github.event_path }}"'
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - name: Checkout via SSH
      run: git clone git@github.com:griff/whitelist.git .

    - uses: cachix/install-nix-action@v7
    - run: 'nix-shell update.nix --command "echo Hello"'
    - run: nix-shell update.nix --run ci/update.sh

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: schedule/update-gems
        branch-suffix: timestamp
