name: "Update Nixpkgs"
on:
  schedule:
    - cron:  '* * * * 4'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v7
    - run: 'nix-shell update.nix --command "echo Hello"'
    - run: 'nix-shell update.nix --command "niv update"'
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: schedule/update-nixpkgs
        branch-suffix: timestamp
